import { GridEvents } from 'muuri'

export interface GridEventHandlerProps {
  onSynchronize?: GridEvents['synchronize']
  onLayoutStart?: GridEvents['layoutStart']
  onLayoutEnd?: GridEvents['layoutEnd']
  onLayoutAbort?: GridEvents['layoutAbort']
  onAdd?: GridEvents['add']
  onRemove?: GridEvents['remove']
  onShowStart?: GridEvents['showStart']
  onShowEnd?: GridEvents['showEnd']
  onHideStart?: GridEvents['hideStart']
  onHideEnd?: GridEvents['hideEnd']
  onFilter?: GridEvents['filter']
  onSort?: GridEvents['sort']
  onMove?: GridEvents['move']
  onSend?: GridEvents['send']
  onBeforeSend?: GridEvents['beforeSend']
  onReceive?: GridEvents['receive']
  onBeforeReceive?: GridEvents['beforeReceive']
  onDragInit?: GridEvents['dragInit']
  onDragStart?: GridEvents['dragStart']
  onDragMove?: GridEvents['dragMove']
  onDragScroll?: GridEvents['dragScroll']
  onDragEnd?: GridEvents['dragEnd']
  onDragReleaseStart?: GridEvents['dragReleaseStart']
  onDragReleaseEnd?: GridEvents['dragReleaseEnd']
  onDestroy?: GridEvents['destroy']
}
